# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Downloads\ProjetAI\qtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
import os
import sys
import pandas as pd
from tensorflow import keras


class Ui_MainWindow1(object):
    def setup(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(530, 280, 211, 31))
        self.lineEdit_7.setStyleSheet("font-size:13pt")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(530, 220, 211, 31))
        self.lineEdit_9.setStyleSheet("font-size:13pt")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 730, 381, 41))
        self.label_11.setStyleSheet("color:rgb(160, 157, 255);font-size:28pt;\n"
"font: 75 italic 28pt \"Lucida Calligraphy\";")
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 220, 111, 31))
        self.label_3.setStyleSheet("color:\n"
"rgb(106, 121, 255)")
        self.label_3.setObjectName("label_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 340, 211, 31))
        self.lineEdit_5.setStyleSheet("font-size:13pt")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 280, 211, 31))
        self.lineEdit_4.setStyleSheet("font-size:13pt")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 400, 131, 41))
        self.pushButton.setStyleSheet("font: 75 italic 12pt \"Lucida Calligraphy\";\n"
"background-color: rgb(125, 142, 255);\n"
"font-size:14pt;\n"
"color: rgb(87, 95, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.test_input())
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(400, 340, 101, 31))
        self.label_7.setStyleSheet("color:\n"
"rgb(106, 121, 255)\n"
"")
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 170, 211, 31))
        self.lineEdit_2.setStyleSheet("font-size:13pt")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 111, 31))
        self.label_5.setStyleSheet("color:\n"
"rgb(106, 121, 255)")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 0, 481, 71))
        self.label_4.setStyleSheet("color:rgb(160, 157, 255);font-size:28pt;\n"
"font: 75 italic 28pt \"Lucida Calligraphy\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(530, 340, 211, 31))
        self.lineEdit_8.setStyleSheet("font-size:13pt")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 280, 131, 31))
        self.label_6.setStyleSheet("color:\n"
"rgb(106, 121, 255)")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 200, 81, 51))
        self.label_8.setStyleSheet("color:\n"
"rgb(106, 121, 255)")
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(530, 170, 211, 31))
        self.lineEdit_6.setStyleSheet("font-size:13pt")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 170, 81, 31))
        self.label_9.setStyleSheet("color:\n"
"rgb(106, 121, 255)\n"
"")
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 220, 211, 31))
        self.lineEdit_3.setStyleSheet("font-size:13pt\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 270, 151, 41))
        self.label_10.setStyleSheet("color:\n"
"rgb(106, 121, 255)")
        self.label_10.setObjectName("label_10")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(650, 720, 161, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0, 330, 131, 41))
        self.label_12.setStyleSheet("color:\n"
"rgb(106, 121, 255)\n"
"")
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 500, 631, 41))
        self.label.setStyleSheet("font: 75 italic 12pt \"MS Shell Dlg 2\";\n"
"font: 87 14pt \"Segoe UI Black\";\n"
"color: rgb(49, 59, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 1471, 91))
        self.label_14.setStyleSheet("color: rgb(143, 139, 255);\n"
"font: 14pt \"Segoe UI Historic\";")
        self.label_14.setObjectName("label_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 400, 131, 41))
        self.pushButton_2.setStyleSheet("font: 75 italic 12pt \"Lucida Calligraphy\";\n"
"background-color: rgb(125, 142, 255);\n"
"font-size:14pt;\n"
"color: rgb(87, 95, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda: self.clearall())
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 400, 171, 41))
        self.pushButton_3.setStyleSheet("font: 75 italic 12pt \"Lucida Calligraphy\";\n"
"background-color: rgb(125, 142, 255);\n"
"font-size:14pt;\n"
"color: rgb(87, 95, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(lambda: self.test_input_deep())
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 400, 171, 41))
        self.pushButton_4.setStyleSheet("font: 75 italic 12pt \"Lucida Calligraphy\";\n"
"background-color: rgb(125, 142, 255);\n"
"font-size:14pt;\n"
"color: rgb(87, 95, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(lambda: self.test_input())
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Results will be displayed here :</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">*Glucose:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Result"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">*Age:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">*Pregnancies:</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Diabetes Prediction</span></p></body></html>"))
        self.label_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Diabets pedigree</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">*Diabets pedigree:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">*BMI:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; font-style:italic;\">*Insulin:</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">*Blood Pressure:</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">*Skin Thickness:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt; font-style:italic;\">We have token all the related factors in its tests and implementing using machine learning techniques by </span></p><p align=\"justify\"><span style=\" font-size:12pt; font-style:italic;\">extracting knowledge from our real health care medical dataset to predict diabetic patients.</span></p><p align=\"justify\"><span style=\" font-size:12pt; font-style:italic;\"/><span style=\" font-size:12pt; font-style:italic;\">Please enter values to predict diabetes!</span></p><p align=\"justify\"><span style=\" font-size:12pt; font-style:italic;\"><br/></span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.pushButton_3.setText(_translate("MainWindow", "deep learning "))
        self.pushButton_4.setText(_translate("MainWindow", "machine learning"))
        
    def check_input(self,data) ->int:
            df=pd.DataFrame(data=data,index=[0])
            with open(r'C:\Users\user\Downloads\ProjetAI\model','rb') as model:
                    p=pickle.load(model)
            op=p.predict(df)
            return op[0]
        
    def check_input_deep(self,data) ->int:
            df=pd.DataFrame(data=data,index=[0])
            p=keras.models.load_model(r'C:\Users\user\Downloads\ProjetAI\savedModel.h5')
            op=p.predict(df)
            return op[0]
    
        
   
    def test_input(self) -> None:
            """ test for diabetes"""
            my_dict = {"B":float(self.lineEdit_2.text()), "C":float(self.lineEdit_3.text()),"D":float(self.lineEdit_4.text()), "E":float(self.lineEdit_5.text()), "F": float(self.lineEdit_6.text()),"G":float(self.lineEdit_9.text()),"H":float(self.lineEdit_7.text()),"I":float(self.lineEdit_8.text())}
            output =self.check_input(my_dict)
            
            #print(self.output)
            #self.setFixedSize(850, 342)
           
            if output==0:
                self.label.setText("Diagnosis suggests that patient does not suffers from diabetes.")
            else:
                self.label.setText("Our diagnosis suggests patient does suffer from diabetes.\nPlease get checked soon.")
    
    def test_input_deep(self) -> None:
            """ test for diabetes"""
            my_dict = {"B":float(self.lineEdit_2.text()), "C":float(self.lineEdit_3.text()),"D":float(self.lineEdit_4.text()), "E":float(self.lineEdit_5.text()), "F": float(self.lineEdit_6.text()),"G":float(self.lineEdit_9.text()),"H":float(self.lineEdit_7.text()),"I":float(self.lineEdit_8.text())}
            output =self.check_input_deep(my_dict)
            
            #print(self.output)
            #self.setFixedSize(850, 342)
           
            print(output*100)
            string = f"indicates that you are  {str(output*100)} % suspected to be diabetic "
            self.label.setText(string)
            
   
    def clearall(self):
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()

        self.lineEdit_6.clear()
        self.lineEdit_9.clear()
        self.lineEdit_7.clear()
        self.lineEdit_8.clear()
        self.my_dict=['','','','','','','','']
        
   
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setup(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
